import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import NavBar from "../components/Navigation/NavBar";
import Footer from "../components/Footer/Footer"
import ThemeProvider from "@/components/ThemeProvider/ThemeProvider";

const poppins = Poppins({ 
  subsets: ["latin"], 
  weight: ["400","500","700","900"],
  style: ["italic","normal"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider>
          <main className="font-normal">
            <NavBar />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
